name: RunProcess_build_test

on:
  push:
    branches-ignore:    
      - main
    paths:
      - 'Frends.Utilities.RunProcess/**'
  workflow_dispatch:

jobs:
  linux_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Utilities.RunProcess
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
  windows_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Utilities.RunProcess
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}