name: Sleep release

on:
  workflow_dispatch:
    paths:
      - 'Frends.Utilities.Sleep/**'
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.Utilities.Sleep
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}