name: ThrowException build push

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Utilities.ThrowException/**'
  workflow_dispatch:
    paths:
      - 'Frends.Utilities.ThrowException/**'
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Utilities.ThrowException
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}